name: sync

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
      - uses: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x
      - name: Deno Build
        run: |
          deno task build
          git config --local user.email "sunclx@gmail.com"
          git config --local user.name "sunclx"
          if [ -n "$(git status -s)" ];then
            git add .
            git commit -a -m "deno build"
          fi
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
